### PR TITLE
moved docu from wiki page to markdown

### PR DESCRIPTION
**Pull request by StefanSpieker**
I converted the documentation from https://wiki.jenkins.io/pages/viewpage.action?pageId=73532011 to two markdown files

### CODE REVIEW

**Comment by michallaskowski** [comment]
Thanks @StefanSpieker . Sorry for keeping you waiting, I just got back from vacation and I am catching up.  I am reading on the wiki changes thread right now. It seems the one image that was there did not get through. Not a huge loss though.

Will you also create an INFRA ticket in Jira after this is merged?
Also, wdyt about waiting with it until #12 is merged (I should be able to review it tomorrow), so that docs can be updated after many changes it brings?

**Comment by StefanSpieker** [comment]
Yes, that is a good idea. I will include the changes after the other PR is merged.

**Comment by michallaskowski** [comment]
@StefanSpieker  Hey. The changes are merged. Let me know if you want to work on wiki and changelog.

**Comment by StefanSpieker** [comment]
I updated the changelog and I will update the documenatation.

**Comment by StefanSpieker** [comment]
I wanted to create a screenshot and set up a new jenkins. But after adding the first project I get an exception:

> Caught exception evaluating: data.jobsPerPlugin in /pluginusage/. Reason: java.lang.reflect.InvocationTargetException
> java.lang.NoClassDefFoundError: hudson/plugins/promoted_builds/PromotedProjectAction
> 	at org.jenkinsci.plugins.pluginusage.analyzer.BuilderJobAnalyzer.processPromotedBuilds(BuilderJobAnalyzer.java:48)
> 	at org.jenkinsci.plugins.pluginusage.analyzer.BuilderJobAnalyzer.doJobAnalyze(BuilderJobAnalyzer.java:42)
> 	at org.jenkinsci.plugins.pluginusage.analyzer.JobCollector.getJobsPerPlugin(JobCollector.java:47)
> 	at org.jenkinsci.plugins.pluginusage.PluginUsageModel.getJobsPerPlugin(PluginUsageModel.java:14)
> Caused: java.lang.reflect.InvocationTargetException

Actually I do not have the time to debug it right now. Maybe you can check the latest version. The Exception is not thrown by the latest release.

**Comment by froque** [comment]
@StefanSpieker Finally had some time to take a look.

I had tried to add dependencies as optional but failed to do it correctly. 

There is a new PR #14 to try and do it well.

**Pull request merged**
