### PR TITLE
Add api support to othersPlugin field in PluginUsageView  

### PR DESCRIPTION
**Pull request by pmarusz**
Hi, i'd like too add OthersPlugin to be accessible from API call.

### Testing done

Running mvn test ends with 13 pass tests. api.json shows how the api works after the change

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by pmarusz** [comment]
[api.json](https://github.com/user-attachments/files/16926372/api.json)

**Comment by pmarusz** [comment]
@froque @michallaskowski

**Comment by froque** [comment]
this is on my todo list. no need to keep pinging me or email me.

**Comment by pmarusz** [comment]
> this is on my todo list. no need to keep pinging me or email me.

Thanks, i thought you missed it somehow

**Pull request merged**
