### PR TITLE
Handle plugins as optional dependencies correctly

### PR DESCRIPTION
**Pull request by froque**
https://wiki.jenkins.io/display/JENKINS/Tips+for+optional+dependencies

### CODE REVIEW

**Comment by aronwk-aaron** [comment]
When will there be a new release with this feature?

**Comment by michallaskowski** [comment]
@aronwk-aaron  I will try to publish tomorrow. To be fair, I don't have much time for this plugin right now, and I was never an expert on Java. @froque since you are already a member of Jenkins, would you be willing to take over this plugin?

**Comment by aronwk-aaron** [comment]
@michallaskowski Apologies if I was acting impatient. I'm looking at upgrading a jenkins instance and trying to figure out plugin support  by hand, and this seemed like a godsend, so I was excited

**Comment by michallaskowski** [comment]
@aronwk-aaron  No, no worries. It was just busy time for me personally and at my day-to-day job. 
If you wish you can also be a maintainer of this plugin and you can push it out, I genuinely would like to hand it over to someone :) I also don't like when I want to use something and I almost can, but it is not published.
I published this plugin once, and to be honest I will need to re-learn how to do it, and even most probably the procedure is a bit different now.

**Comment by aronwk-aaron** [comment]
@michallaskowski Unfortunately, I am not a Java dev, otherwise I would

**Comment by froque** [comment]
@michallaskowski yep, sure, I can take over. will start the process.

**Comment by froque** [comment]
@michallaskowski please confirm at https://github.com/jenkins-infra/repository-permissions-updater/pull/1442

**Pull request merged**
